PRX/cms.theworld.org

.vscode/settings.json, wp-config-production.php, wp-content/plugins/fg-drupal-to-wp-premium/admin/class-fg-drupal-to-wp-admin.php, wp-content/plugins/fg-drupal-to-wp-premium/admin/class-fg-drupal-to-wp-premium-admin.php, wp-content/plugins/fg-drupal-to-wp-premium/admin/partials/admin-display.php, wp-content/plugins/fg-drupal-to-wp-premium/admin/partials/import-control.php, wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php, wp-content/plugins/pri-migration-helper/admin/includes/js/post-worker.js, wp-content/plugins/pri-migration-helper/admin/parts/main.php
- New way to control how many items we are going to migrate per process
- Process to import redirect aliases 
- Increase Memory Limit to 512MB
=> Import control

wp-content/plugins/pri-migration-helper/migration/media_filters/media-segment-filters.php
Store the correct Drupal file id for segments
=> Fix file id stored for segments

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
Closes #[ISSUE_ID]
- [List what the PR does...]
> ...then...
=> disable Admin Columns plugin to test post page performance

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php, wp-content/plugins/tw-import-post-types/tw-import-post-types.php
- Add custom post types "Person" and "Program" to be removed after the import is complete in live environment.
=> Add temporary custom post types Person and Program.

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php, wp-content/plugins/tw-disable-yoast-indexables/tw-disable-yoast-indexables.php
- Disable Automatic Yoast Indexable Feature.
=> Disable Automatic Yoast Indexable Feature

wp-content/plugins/pri-migration-helper/admin/admin.php, wp-content/plugins/pri-migration-helper/admin/includes/acf-fix-helper.php, wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php, wp-content/plugins/pri-migration-helper/admin/includes/js/acf-fix.js, wp-content/plugins/pri-migration-helper/admin/includes/js/media-fix.js, wp-content/plugins/pri-migration-helper/admin/parts/acf-fix.php, wp-content/plugins/pri-migration-helper/admin/parts/media-fix.php
- Fix Media Size
-  Fix image block to include caption, sizes and display it as Gutenberg block
- Fix to include ACF fields in the API response
=> Fix media image block, image size and acf api fields

wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php, wp-content/plugins/pri-migration-helper/admin/includes/css/admin-styling-css.css, wp-content/plugins/pri-migration-helper/admin/includes/js/media-fix.js, wp-content/plugins/pri-migration-helper/admin/parts/cron.php, wp-content/plugins/pri-migration-helper/admin/parts/media-fix.php
- Improve speed for media fix size and tags
- Add daily cron support for media fix process
=> Improve media fix and add cron support

wp-content/plugins/fg-drupal-to-wp-premium/includes/class-fg-drupal-to-wp-premium.php, wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php, wp-content/plugins/pri-migration-helper/admin/includes/js/acf-fix.js, wp-content/plugins/pri-migration-helper/admin/includes/js/media-fix.js, wp-content/plugins/pri-migration-helper/admin/parts/media-fix.php, wp-content/plugins/tw-disable-yoast-indexables/tw-disable-yoast-indexables.php
- Create an UI interface to activate/deactivate the trigger for Yoast indexable feature when you access to WP Admin.
- Changes in the code to improve Media HTML Content fix.
=> Yoast ui to enable/disable indexation, media fix query improvements

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php, wp-content/mu-plugins/the-world-site-config/configs/production/production-config.php, wp-content/plugins/wp-redis/cli.php, wp-content/plugins/wp-redis/object-cache.php, wp-content/plugins/wp-redis/readme.txt, wp-content/plugins/wp-redis/wp-redis.php
- Upgrade Redis Plugin to V1.4.3
- Active Redis Plugin
- Code to avoid CONSTANT warning stored in the logs.
=> Enable redis

wp-content/plugins/tw-custom-tags/taxonomies/taxonomy-person.php, wp-content/plugins/tw-endpoint-helper/includes/class-peh-alias-object.php, wp-content/plugins/tw-endpoint-helper/includes/peh-get-object-wild.php, wp-content/plugins/tw-endpoint-helper/tw-endpoint-helper.php, wp-content/plugins/tw-import-post-types/tw-import-post-types.php, wp-content/plugins/tw-programs/tw-programs.php
- Fix program path when calling it from tw alias endpoint
- Fix person path when calling it from tw alias endpoint
=> Fix Person and Program endpoint

wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php, wp-content/plugins/pri-migration-helper/cli/cli.php, wp-content/plugins/pri-migration-helper/cli/includes/class-pmh-worker.php
- Implement new logic to detect file types and use the audio shortcode when it is a mp3
- Add code to replace img tag for mp3 files with the correct audio shortcode.
=> Fix media import to support audio detection

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php, wp-content/plugins/tw-endpoint-helper/includes/class-peh-alias-object.php, wp-content/plugins/tw-endpoint-helper/tw-endpoint-helper.php
- Adds support for person taxonomy using "tags/people/PEOPLE_SLUG" as slug in the alias endpoint.
- Re-enable Person and Program post needed in migration process.
=> Support tags/people prefix for person taxonomy in the alias API endpoint

wp-content/themes/the-world/functions.php, wp-content/themes/the-world/style.css
- Updates posts lists tables for a more readable layout across screen sizes..
> ...then...
=> BONUS: Update Posts List Table Layout

wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php
- Insert Gutenberg Image block instead img tag in future imports.
- Apply correct css classes depending on what's class included in Drupal.
- Remove the extra paragraph around image block.
- Update the method used by wp-cli command to fix images already imported.
=> Fix and Replace img tag by image block

wp-content/plugins/pri-migration-helper/cli/cli.php, wp-content/plugins/pri-migration-helper/cli/includes/class-pmh-worker.php, wp-content/plugins/pri-migration-helper/migration/media_filters/media-global-filters.php
- Creates a process to fix image caption for images already imported
- Add the fix for new imported images
=> Fix Image Caption

wp-content/plugins/fg-drupal-to-wp-premium/admin/class-fg-drupal-to-wp-admin.php, wp-content/plugins/pri-migration-helper/migration/migration.php
- Replace Drupal image placeholder by image tags inside taxonomy term description.
- Support HTML tags in the description
=> Improve the import term description to include Drupal images

wp-content/themes/the-world/functions.php
- Updates TW Homepage link after migration
> ...then...
=> HOTFIX: Update The World Homepage link

wp-content/themes/the-world/functions.php
adjusting position of relative link
=> fix(hp-link): take 2

wp-config-constants.php, wp-config-pantheon.php, wp-config.php
- Check for existence of `secrets.json` file in Pantheon environments.
- Decode file contents and convert key/values into environment variables.
=> HOTFIX: config: parse secrets.json into env vars

wp-content/plugins/fg-drupal-to-wp-premium/admin/class-fg-drupal-to-wp-admin.php
Add support for single story import
=> Single import

wp-config-production.php
- configure S3 upload bucket URL to use `media.pri.org` domain
=> config: define S3 upload bucket URL

wp-content/plugins/tw-endpoint-helper/tw-endpoint-helper.php
- Escape slug when checking for old url or aliases.
=> Escape slug when doing cusotm queries

wp-content/plugins/tw-endpoint-helper/tw-endpoint-helper.php
- Modify Url filter to detect Segment Post when the alias has `media/` prefix
- Add extra args to the get_posts query to make it faster
=> Add media url filter to detect segments

wp-content/plugins/tw-endpoint-helper/includes/class-peh-url-to-query-item.php, wp-content/plugins/tw-endpoint-helper/tw-endpoint-helper.php
=> HOTFIX: Alias API support numeric slug

.github/workflows/main.yml, .github/workflows/multidev.yml
- Upgrade PHP version from 8.1 to 8.2 required by github actions.
- Merge the PR and check that github action works properly.
=> Upgrade github workflows PHP version
