PRX/cms.theworld.org

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/tw-endpoint-helper/includes/class-peh-alias-object.php
wp-content/plugins/tw-endpoint-helper/tw-endpoint-helper.php

- Create a WP API endpoint to receive an alias slug and return the proper WP object or an external url redirect if it match with any.

Add API enpoint to return WP resources from different url alias

---

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/wp-rest-menu/includes/class-webfiou-wp-rest-menus-controller.php
wp-content/plugins/wp-rest-menu/includes/index.php
wp-content/plugins/wp-rest-menu/index.php
wp-content/plugins/wp-rest-menu/readme.txt
wp-content/plugins/wp-rest-menu/wp-rest-menus.php

Closes #59 
- Installs WP REST menu
- I added all the menus and items to the live env (the latest db backup from live will include the items)
> ...then...

#59 Install and enable wp-rest-menu

---

wp-content/mu-plugins/the-world-site-config/configs/development/development-plugins.php
wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php

Closes #91 
- Moves Custom Post Type UI plugin to development and commented it out. We can turn it on when we need it.
> ...then...

#91 Disable Custom Post Type UI plugin

---

wp-content/plugins/tw-episodes/tw-episodes.php
wp-content/themes/newspack-theme/acf-json/group_622a1664a8c12.json

- Enable excerpt for Episodes post type.
- Remove teaser ACF field from Episodes because the Drupal teaser was moved to the excerpt post field.

Enable excerpt and remove teaser acf field from episodes

---

wp-content/plugins/fg-drupal-to-wp-premium/admin/class-fg-drupal-to-wp-admin.php
wp-content/plugins/pri-migration-helper/cli/cli.php
wp-content/plugins/pri-migration-helper/cli/includes/class-pmh-worker.php
wp-content/plugins/pri-migration-helper/migration/migration.php
wp-content/plugins/pri-migration-helper/pri-migration-helper.php

- Add a new WP CLI command that facilitates the adjustment of image sizes directly from terminal commands. Additionally, the same process has been set to trigger automatically upon a Drupal import is finished.

Add a wp cli command to read amazon images and fix their sizes

---

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/tw-custom-tags/taxonomies/taxonomy-city.php
wp-content/plugins/tw-custom-tags/taxonomies/taxonomy-continent.php
wp-content/plugins/tw-custom-tags/taxonomies/taxonomy-country.php
wp-content/plugins/tw-custom-tags/taxonomies/taxonomy-person.php
wp-content/plugins/tw-custom-tags/taxonomies/taxonomy-province-state.php
wp-content/plugins/tw-custom-tags/taxonomies/taxonomy-region.php
wp-content/plugins/tw-custom-tags/taxonomies/taxonomy-social-tag.php
wp-content/plugins/tw-episodes/tw-episodes.php
wp-content/plugins/tw-segments/tw-segments.php

Closes #121 
- Updates tw-custom-tags taxonomies to apply to episode and segment post types.
- Updates tw-custom-tags taxonomies' rest base paths.
> ...then...

121: Add custom taxonomies to episode and segment

---

wp-content/themes/the-world/acf-json/group_622a31617f10b.json
wp-content/themes/the-world/acf-json/group_622a32ff021a3.json

Closes #124 
- Rename "Program Hosts" field group to "Program Contributors"
- Add Team field to "Program Contributors"
- Update program fields groups presentation
> ...then...

124: Add Team field to Program terms

---

wp-content/themes/the-world/functions.php

Closes #66 
- [Removes WLW manifest link from site header](https://wpassist.me/how-to-remove-wlwmanifest-from-wordpress/)

#66 remove wlw manifest link from site header

---

wp-content/mu-plugins/the-world-site-config/configs/production/production-config.php

Closes #95 
- To my eye it looks like loading an empty staging config file is causing a warning that may become an error down the road. This PR comments out the part that loads this file. 
- If you have another solution in looking, feel free to adjust.

#95: don't load empty staging config file

---

wp-content/themes/the-world/functions.php

- yoast container height
- categories metabox height
> ...then...

HOTFIX: admin accordion content heights

---

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/tw-call-to-actions/post-types/post-type--cta-region.php
wp-content/plugins/tw-call-to-actions/post-types/post-type--cta.php
wp-content/plugins/tw-call-to-actions/taxonomies/taxonomy--cta-region-type.php
wp-content/plugins/tw-call-to-actions/tw-call-to-actions.php
wp-content/themes/the-world/acf-json/group_622a2d2e34139.json
wp-content/themes/the-world/acf-json/group_64e6466148253.json
wp-content/themes/the-world/acf-json/group_64e658ff75bf6.json
wp-content/themes/the-world/acf-json/group_64e7874e3237c.json
wp-content/themes/the-world/acf-json/group_64e788ab4e23b.json

Closes #10 
- add call_to_action post type
- add cta_region post type
- add cta_region_type taxonomy
- config acf fields for call_to_action posts
- config acf fields for cta_region posts
> ...then...
```
query getCtaRegions {
callToActions(first: 10) {
nodes {
... CtaProps
}
}
ctaRegion(id: "site-banner", idType: SLUG) {
... CtaRegionProps
}
ctaRegionType(id: "site", idType: SLUG) {
id
name
ctaRegions {
nodes {
... CtaRegionProps
}
}
}
}
fragment CtaRegionProps on CtaRegion {
id
title
slug
ctaRegionContent {
callToActions {
... CtaProps
}
}
}
fragment CtaProps on CallToAction {
ctaOptions {
ctaType
content {
heading
message
}
actions {
actionButtonLabel
actionButtonUrl
dismissButtonLabel
}
optInSettings {
optInText
}
newsletterSettings {
newsletter {
... on Newsletter {
id
title …
```

10: Create Call To Actions plugin

---

wp-config-development.php
wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/tw-graphql/tw-graphql.php
wp-content/plugins/tw-programs/tw-programs.php

Closes #103 
- add tw-graphql plugin to own graphql api modifications
- add primary term fields to post types for hierarchical taxonomies
- move `programNotIn` filter arg registration to tw-graphql plugin
> ...then...
```
query GetPosts {
posts {
nodes {
id
title
slug
primaryCategory {
id
name
}
}
}
}
```
> Currently the only hierarchical taxonomy we use is categories. If we ever add a hierarchical taxonomy in the future, a primary term field for that taxonomy will be added to post types using the taxonomy.

103: Add Primary Term fields to post types for hierarchical taxonomies

---

wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php
wp-content/plugins/pri-migration-helper/cli/includes/class-pmh-worker.php

- In image size fix process add different ways to encode the url before reading the image from S3 because wp esc_url method generates some encodes with wrong encoded characters.
- In the mp3 content fix add a way to validate that the file name exists in the S3 server before using the path.

Add logic to encode image url in different ways before importing

---

wp-content/plugins/pri-migration-helper/cli/includes/class-pmh-worker.php

- Avoid the wp cli process stop when the post content does not contain image tags.

Do not stop wpcli when post not updated or does not exists

---

wp-content/plugins/pri-migration-helper/README.md
wp-content/plugins/pri-migration-helper/cli/cli.php
wp-content/plugins/pri-migration-helper/cli/includes/class-pmh-worker.php

- Loop Post Tags searching duplicated slugs in Custom Taxonomies
- Associate Posts and Episodes to Custom taxonomies found as duplicated elements with Post Tags
- Remove the Association between duplicated Post Tags and Posts and Episodes
IMPORTANT: If the Post Tag is repeated in more than 1 custom taxonomy, for example Countries, Categories and Social Tags, the Posts and Episodes will be associated to the 3 of them.

Cleanup Post Tags

---

wp-content/themes/the-world/css/block-editor.css
wp-content/themes/the-world/css/editor.css
wp-content/themes/the-world/js/blockembed.js

- enables Spotify embed blocks
- update alignment styles to better support Spotify embeds
> ...then...

feat(theworld): enable spotify embeds

---

wp-content/plugins/pri-migration-helper/migration/taxonomy_filters/taxonomy-category.php

- Change the code to use Drupal Category Body field for those categories where the description is empty.

Use category body field as description only when description is empty

---

wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php
wp-content/plugins/pri-migration-helper/migration/media_filters/media-global-filters.php
wp-content/plugins/pri-migration-helper/migration/migration.php

This PR includes the image size fix as part of the normal import and disable the process which does the same at the end of the import to avoid trying to fix the size twice.

Include fix image size attributes in the normal import process

---

.vscode/settings.json
wp-content/themes/the-world/functions.php

- Adds admin sidebar link to TW Program page for easier access to curate homepage
> ...then...

Adds admin sidebar link to TW Program page

---

wp-content/plugins/pri-migration-helper/README.md
wp-content/plugins/pri-migration-helper/admin/includes/admin-page.php
wp-content/plugins/pri-migration-helper/admin/parts/selective-fix.php
wp-content/plugins/pri-migration-helper/cli/cli.php
wp-content/plugins/pri-migration-helper/cli/includes/class-pmh-worker.php
wp-content/plugins/pri-migration-helper/migration/migration.php

- WP CLI command `repair_wp_fg_redirect_tables`  to create relationship between Drupal node and WP ID.
- WP CLI command `update_url_alias_table`  to create all the aliases added to Drupal url alias table.
- WP Admin UI that will allow us to setup specific Drupal IDs to be migrated, this will be useful in case we need to test something.
WP CLI commands were added to the client documentation and also to the Migration Document.

Redirects tables and tool to update single elements

---

private/config/dev
private/config/live

In Pantheon all folders inside `code` are not writeable, so, we need symbolic links to `files` folder to make them writeable.

Add symbolic links to enable environment writable folders

---

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/PATCH-s3-uploads/s3-uploads.php

- Uploads files to s3 bucket (the plugin was not in the global-plugins file and thusly not activated.
> ...then...

Activate Patched S3 Upload plugin

---

wp-content/plugins/pri-migration-helper/migration/media_filters/media-global-filters.php

- When images processed from Drupal does not have meta data, download the file and get the size from there.
- To avoid fatal errors, a default size as 2560px width and height was added in case the download file fails.
- New post meta `_temp_import_image_size_from_download` was added to store the sizes returned from the downloaded file in case we want to use as debug. This key was added to the list of metas to be removed.

Add download media to get its size if it does not exist in drupal

---

wp-content/plugins/tw-image-credit/tw-image-credit.php
wp-content/themes/the-world/acf-json/group_62b485f48c100.json
wp-content/themes/the-world/acf-json/group_62d671b9ba699.json
wp-content/themes/the-world/functions.php

Closes #205 
- add image credit url field
- update image field groups to display in block editor dialogs
- add field descriptions to image fields
> ...then...

205: Add image credit URL field

---

scripts/refresh.sh
wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/tw-acf-sync-helper/tw-acf-sync-helper.php

Closes #[169]
- Add a new plugin to create a wp-cli command. The command will synchronize ACF groups when there is a sync available.
- Add WP-CLI ACF sync command to the refresh script
There is a command example in the plugin code.

Add WP-CLI command to sync ACF groups automatically

---

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/tw-sitemap-mask/tw-sitemap-mask.php

Closes #[197]
- Add the  plugin "TW Sitemap Mask"  with a setting to set the proper domain to be used in sitemap links.
We are replacing `get_bloginfo( 'url' );` by the url set in the setting. The `get_bloginfo( 'url' );` should return the current domain used in the browser that is gonna be replaced by the custom.

Add the option to overwrite domains in sitemap links

---

.github/workflows/multidev.yml

Closes #WP-311
Closes #90 
- Push code to Pantheon Dev repository when pushing code or merging a PR to the main repo.
- Deploy code to Pantheon Test repository when pushing code  or merging a PR to the main repo and the commit message includes `[deploy:test]`
- Deploy code to Pantheon Live repository when pushing code  or merging a PR to the main repo and the commit message includes `[deploy:live]`
- Create a multidev environment based on live and push the code of that branch to Pantheon new environment when a branch name uses `multidev-` as prefix. 
For example `multidev-test` will try to create a multidev environment called `test` and then will push the code of the github branch to that environment. If a multidev environment already exists with that name, it is going to use the existing …

Improvements in Pantheon automatic deploy

---

wp-content/mu-plugins/the-world-site-config/configs/global/global-plugins.php
wp-content/plugins/tw-rss-helper/includes/rss.php
wp-content/plugins/tw-rss-helper/tw-rss-helper.php

Closes #249 
- Add enclosure tag based on a post audio meta.

#249 Add Audio Enclosures to RSS Feeds
